'use client'
import { motion } from 'framer-motion'
import { useEffect, useRef, useState, useCallback } from 'react'
import { Check, Clock, Target, BookOpen, Dumbbell, Brain, Calendar, Plus, Trash2, Edit2, Save, X, ChevronDown, ChevronUp, Sparkles, TrendingUp, Award, AlertCircle, CheckCircle2, Circle, Play, Pause, RotateCcw, Filter, Search, Download, ZoomIn, ZoomOut, Maximize2, Info, Eye, EyeOff, Sliders, Lightbulb, Flame, Star, ArrowRight, ArrowUp, ArrowDown, Minus, BarChart3, LineChart, PieChart } from 'lucide-react'
import { useAuth } from '@/lib/auth'

export default function DailyPlanDashboard({ studyLogs, tasks, goals, habits, exercise, meditation, stats, onPlanUpdate, onTaskComplete }) {
  const { token } = useAuth()
  const [plan, setPlan] = useState(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [showPlanInput, setShowPlanInput] = useState(false)
  const [planInput, setPlanInput] = useState({
    studyTopics: '',
    studyHours: 2,
    exerciseType: '',
    exerciseMinutes: 30,
    meditationMinutes: 15,
    tasks: '',
    goals: '',
    habits: '',
    priority: 'medium'
  })
  const [completedItems, setCompletedItems] = useState({})
  const [progress, setProgress] = useState(0)
  const [analytics, setAnalytics] = useState(null)
  const [viewMode, setViewMode] = useState('checklist') // checklist, timeline, stats
  const [filterStatus, setFilterStatus] = useState('all') // all, pending, completed
  const [searchQuery, setSearchQuery] = useState('')
  const [showDetails, setShowDetails] = useState(true)

  // Load existing plan from API on mount
  useEffect(() => {
    const loadExistingPlan = async () => {
      if (!token) return
      try {
        const response = await fetch('/api/daily-plans', {
          headers: token ? { 'Authorization': `Bearer ${token}` } : {}
        })
        if (response.ok) {
          const data = await response.json()
          if (data.todayPlan) {
            setPlan(data.todayPlan)
            setCompletedItems(data.todayPlan.completedItems || {})
          }
        }
      } catch (error) {
        console.error('Failed to load existing plan:', error)
      }
    }

    loadExistingPlan()
  }, [token])
  
  // Calculate progress
  useEffect(() => {
    if (!plan) return
    
    const totalItems = plan.items?.length || 0
    const completedCount = Object.values(completedItems).filter(Boolean).length
    const progressPercent = totalItems > 0 ? (completedCount / totalItems) * 100 : 0
    setProgress(progressPercent)
    
    // Calculate analytics
    const analyticsData = calculatePlanAnalytics(plan, completedItems)
    setAnalytics(analyticsData)
  }, [plan, completedItems])
  
  const calculatePlanAnalytics = (planData, completedData) => {
    if (!planData) return null
    
    const items = planData.items || []
    const totalItems = items.length
    const completedCount = Object.values(completedData).filter(Boolean).length
    
    const byCategory = {
      study: { total: 0, completed: 0 },
      exercise: { total: 0, completed: 0 },
      meditation: { total: 0, completed: 0 },
      tasks: { total: 0, completed: 0 },
      habits: { total: 0, completed: 0 },
      goals: { total: 0, completed: 0 }
    }
    
    items.forEach(item => {
      if (byCategory[item.category]) {
        byCategory[item.category].total++
        if (completedData[item.id]) {
          byCategory[item.category].completed++
        }
      }
    })
    
    const completionRate = totalItems > 0 ? (completedCount / totalItems) * 100 : 0
    
    return {
      totalItems,
      completedCount,
      completionRate,
      byCategory,
      estimatedTime: items.reduce((sum, item) => sum + (item.duration || 0), 0),
      priorityDistribution: {
        high: items.filter(i => i.priority === 'high').length,
        medium: items.filter(i => i.priority === 'medium').length,
        low: items.filter(i => i.priority === 'low').length
      }
    }
  }
  
  const generatePlan = async () => {
    if (!token) return
    setIsGenerating(true)

    try {
      // Try AI-powered generation first
      const response = await fetch('/api/ai/generate-daily-plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...(token ? { 'Authorization': `Bearer ${token}` } : {}) },
        body: JSON.stringify({
          ...planInput,
          userData: { studyLogs, tasks, goals, habits, exercise, meditation, stats }
        })
      })

      if (response.ok) {
        const data = await response.json()
        const aiPlan = {
          id: Date.now().toString(),
          date: new Date().toISOString().slice(0, 10),
          title: data.plan.title || 'AI-Generated Daily Plan',
          description: data.plan.description || 'Personalized plan generated by AI',
          items: data.plan.items || [],
          completedItems: {},
          progress: 0,
          metadata: {
            generatedAt: new Date().toISOString(),
            source: 'AI',
            version: '1.0'
          }
        }

        // Save to API
        const saveResponse = await fetch('/api/daily-plans', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', ...(token ? { 'Authorization': `Bearer ${token}` } : {}) },
          body: JSON.stringify(aiPlan)
        })

        if (saveResponse.ok) {
          const savedPlan = await saveResponse.json()
          setPlan(savedPlan)
          setCompletedItems(savedPlan.completedItems || {})
        } else {
          setPlan(aiPlan)
        }

        setIsGenerating(false)
        setShowPlanInput(false)

        if (onPlanUpdate) {
          onPlanUpdate(aiPlan)
        }
        return
      }
    } catch (error) {
      console.error('AI generation failed, falling back to local generation:', error)
    }
    
    // Fallback to local generation
    setTimeout(async () => {
      const generatedPlan = {
        id: Date.now().toString(),
        date: new Date().toISOString().slice(0, 10),
        title: 'Daily Plan',
        description: 'AI-generated personalized plan based on your goals',
        items: generatePlanItems(planInput),
        completedItems: {},
        progress: 0,
        metadata: {
          generatedAt: new Date().toISOString(),
          source: 'Local',
          version: '1.0'
        }
      }
      
      // Save to API
      try {
        const response = await fetch('/api/daily-plans', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(generatedPlan)
        })
        
        if (response.ok) {
          const savedPlan = await response.json()
          setPlan(savedPlan)
          setCompletedItems(savedPlan.completedItems || {})
        } else {
          setPlan(generatedPlan)
        }
      } catch (error) {
        console.error('Failed to save plan:', error)
        setPlan(generatedPlan)
      }
      
      setIsGenerating(false)
      setShowPlanInput(false)
      
      if (onPlanUpdate) {
        onPlanUpdate(generatedPlan)
      }
    }, 1500)
  }
  
  const generatePlanItems = (input) => {
    const items = []
    let itemId = 0
    
    // Study items
    if (input.studyTopics) {
      const topics = input.studyTopics.split(',').map(t => t.trim()).filter(t => t)
      topics.forEach(topic => {
        items.push({
          id: `study-${itemId++}`,
          type: 'study',
          category: 'study',
          title: `Study: ${topic}`,
          description: `Focus on ${topic} for ${input.studyHours} hours`,
          duration: input.studyHours * 60,
          priority: input.priority,
          completed: false,
          timeSlot: 'morning',
          estimatedImpact: 'high'
        })
      })
    }
    
    // Exercise items
    if (input.exerciseType) {
      items.push({
        id: `exercise-${itemId++}`,
        type: 'exercise',
        category: 'exercise',
        title: `Exercise: ${input.exerciseType}`,
        description: `${input.exerciseMinutes} minutes of ${input.exerciseType}`,
        duration: input.exerciseMinutes,
        priority: input.priority === 'high' ? 'high' : 'medium',
        completed: false,
        timeSlot: 'afternoon',
        estimatedImpact: 'medium'
      })
    }
    
    // Meditation items
    if (input.meditationMinutes > 0) {
      items.push({
        id: `meditation-${itemId++}`,
        type: 'meditation',
        category: 'meditation',
        title: 'Meditation Session',
        description: `${input.meditationMinutes} minutes of mindfulness meditation`,
        duration: input.meditationMinutes,
        priority: 'medium',
        completed: false,
        timeSlot: 'evening',
        estimatedImpact: 'high'
      })
    }
    
    // Task items
    if (input.tasks) {
      const taskList = input.tasks.split(',').map(t => t.trim()).filter(t => t)
      taskList.forEach(task => {
        items.push({
          id: `task-${itemId++}`,
          type: 'task',
          category: 'tasks',
          title: task,
          description: 'Complete this task',
          duration: 30,
          priority: input.priority,
          completed: false,
          timeSlot: 'flexible',
          estimatedImpact: 'medium'
        })
      })
    }
    
    // Goal items
    if (input.goals) {
      const goalList = input.goals.split(',').map(g => g.trim()).filter(g => g)
      goalList.forEach(goal => {
        items.push({
          id: `goal-${itemId++}`,
          type: 'goal',
          category: 'goals',
          title: `Progress on: ${goal}`,
          description: 'Take a step towards this goal',
          duration: 45,
          priority: 'high',
          completed: false,
          timeSlot: 'flexible',
          estimatedImpact: 'high'
        })
      })
    }
    
    // Habit items
    if (input.habits) {
      const habitList = input.habits.split(',').map(h => h.trim()).filter(h => h)
      habitList.forEach(habit => {
        items.push({
          id: `habit-${itemId++}`,
          type: 'habit',
          category: 'habits',
          title: habit,
          description: 'Maintain this habit',
          duration: 15,
          priority: 'medium',
          completed: false,
          timeSlot: 'daily',
          estimatedImpact: 'medium'
        })
      })
    }
    
    return items
  }
  
  const toggleItemComplete = async (itemId) => {
    if (!token) return
    const newCompleted = !completedItems[itemId]
    const newCompletedItems = {
      ...completedItems,
      [itemId]: newCompleted
    }
    setCompletedItems(newCompletedItems)

    // Try to update via API if plan has an ID
    if (plan?.id && typeof plan.id === 'string') {
      try {
        const response = await fetch(`/api/daily-plans/${plan.id}/complete`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', ...(token ? { 'Authorization': `Bearer ${token}` } : {}) },
          body: JSON.stringify({ itemId, completed: newCompleted })
        })

        if (response.ok) {
          const updatedPlan = await response.json()
          setPlan(updatedPlan)
          setCompletedItems(updatedPlan.completedItems || {})
        }
      } catch (error) {
        console.error('Failed to update via API:', error)
      }
    }
    
    // Notify parent component
    if (onTaskComplete) {
      const item = plan?.items?.find(i => i.id === itemId)
      onTaskComplete(itemId, newCompleted, item)
    }
  }
  
  const addItem = (category, title) => {
    if (!plan || !title) return
    
    const newItem = {
      id: `manual-${Date.now()}`,
      type: category,
      category,
      title,
      description: 'Manually added item',
      duration: 30,
      priority: 'medium',
      completed: false,
      timeSlot: 'flexible',
      estimatedImpact: 'medium'
    }
    
    setPlan({
      ...plan,
      items: [...plan.items, newItem]
    })
  }
  
  const removeItem = (itemId) => {
    if (!plan) return
    
    setPlan({
      ...plan,
      items: plan.items.filter(item => item.id !== itemId)
    })
    
    // Remove from completed items
    const newCompletedItems = { ...completedItems }
    delete newCompletedItems[itemId]
    setCompletedItems(newCompletedItems)
  }
  
  const exportPlan = () => {
    if (!plan) return
    
    const data = {
      plan,
      completedItems,
      progress,
      analytics,
      exportDate: new Date().toISOString()
    }
    
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
    const link = document.createElement('a')
    link.download = `daily-plan-${new Date().toISOString().split('T')[0]}.json`
    link.href = URL.createObjectURL(blob)
    link.click()
  }
  
  const filteredItems = plan?.items?.filter(item => {
    if (searchQuery && !item.title.toLowerCase().includes(searchQuery.toLowerCase())) {
      return false
    }
    
    if (filterStatus === 'pending' && completedItems[item.id]) {
      return false
    }
    
    if (filterStatus === 'completed' && !completedItems[item.id]) {
      return false
    }
    
    return true
  }) || []
  
  const getCategoryIcon = (category) => {
    const icons = {
      study: BookOpen,
      exercise: Dumbbell,
      meditation: Brain,
      tasks: Target,
      goals: Award,
      habits: Flame
    }
    return icons[category] || Circle
  }
  
  const getCategoryColor = (category) => {
    const colors = {
      study: 'text-violet-400 bg-violet-500/20 border-violet-500/30',
      exercise: 'text-emerald-400 bg-emerald-500/20 border-emerald-500/30',
      meditation: 'text-cyan-400 bg-cyan-500/20 border-cyan-500/30',
      tasks: 'text-amber-400 bg-amber-500/20 border-amber-500/30',
      goals: 'text-pink-400 bg-pink-500/20 border-pink-500/30',
      habits: 'text-orange-400 bg-orange-500/20 border-orange-500/30'
    }
    return colors[category] || 'text-gray-400 bg-gray-500/20 border-gray-500/30'
  }
  
  const getPriorityColor = (priority) => {
    const colors = {
      high: 'text-red-400',
      medium: 'text-amber-400',
      low: 'text-green-400'
    }
    return colors[priority] || 'text-gray-400'
  }
  
  if (!plan && !showPlanInput) {
    return (
      <div className="w-full h-full min-h-[600px] bg-black/40 rounded-2xl overflow-hidden border border-white/10 p-8">
        <div className="flex flex-col items-center justify-center h-full">
          <motion.div
            animate={{ 
              scale: [1, 1.1, 1],
              rotate: [0, 10, -10, 0]
            }}
            transition={{ duration: 4, repeat: Infinity }}
            className="text-6xl mb-4"
          >
            📋
          </motion.div>
          <h2 className="text-2xl font-bold text-white mb-2">No Active Plan</h2>
          <p className="text-white/60 text-sm mb-6">Generate your personalized daily plan with AI</p>
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={() => setShowPlanInput(true)}
            className="px-6 py-3 rounded-xl bg-gradient-to-r from-violet-500 to-cyan-500 text-white font-medium flex items-center gap-2"
          >
            <Sparkles className="w-5 h-5" />
            Generate Plan
          </motion.button>
        </div>
      </div>
    )
  }
  
  if (showPlanInput) {
    return (
      <div className="w-full h-full min-h-[600px] bg-black/40 rounded-2xl overflow-hidden border border-white/10 p-6">
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-violet-400" />
            Generate Your Plan
          </h2>
          <button
            onClick={() => setShowPlanInput(false)}
            className="p-2 rounded-lg hover:bg-white/10 transition-colors"
          >
            <X className="w-5 h-5 text-white/60" />
          </button>
        </div>
        
        <div className="space-y-4 max-h-[500px] overflow-y-auto">
          <div className="glass-card rounded-xl p-4 space-y-3">
            <div className="flex items-center gap-2 mb-2">
              <BookOpen className="w-4 h-4 text-violet-400" />
              <label className="text-sm font-medium text-white">Study Topics</label>
            </div>
            <input
              type="text"
              placeholder="e.g., Mathematics, Physics, Programming (comma separated)"
              value={planInput.studyTopics}
              onChange={(e) => setPlanInput({ ...planInput, studyTopics: e.target.value })}
              className="w-full px-3 py-2 rounded-lg bg-black/40 border border-white/10 text-white text-sm outline-none focus:border-violet-500/50"
            />
            <div className="flex items-center gap-2">
              <Clock className="w-4 h-4 text-white/60" />
              <span className="text-xs text-white/60">Hours:</span>
              <input
                type="number"
                min="0.5"
                max="12"
                step="0.5"
                value={planInput.studyHours}
                onChange={(e) => setPlanInput({ ...planInput, studyHours: parseFloat(e.target.value) })}
                className="w-20 px-2 py-1 rounded-lg bg-black/40 border border-white/10 text-white text-sm outline-none focus:border-violet-500/50"
              />
            </div>
          </div>
          
          <div className="glass-card rounded-xl p-4 space-y-3">
            <div className="flex items-center gap-2 mb-2">
              <Dumbbell className="w-4 h-4 text-emerald-400" />
              <label className="text-sm font-medium text-white">Exercise</label>
            </div>
            <input
              type="text"
              placeholder="e.g., Running, Yoga, Weight Training"
              value={planInput.exerciseType}
              onChange={(e) => setPlanInput({ ...planInput, exerciseType: e.target.value })}
              className="w-full px-3 py-2 rounded-lg bg-black/40 border border-white/10 text-white text-sm outline-none focus:border-emerald-500/50"
            />
            <div className="flex items-center gap-2">
              <Clock className="w-4 h-4 text-white/60" />
              <span className="text-xs text-white/60">Minutes:</span>
              <input
                type="number"
                min="5"
                max="180"
                step="5"
                value={planInput.exerciseMinutes}
                onChange={(e) => setPlanInput({ ...planInput, exerciseMinutes: parseInt(e.target.value) })}
                className="w-20 px-2 py-1 rounded-lg bg-black/40 border border-white/10 text-white text-sm outline-none focus:border-emerald-500/50"
              />
            </div>
          </div>
          
          <div className="glass-card rounded-xl p-4 space-y-3">
            <div className="flex items-center gap-2 mb-2">
              <Brain className="w-4 h-4 text-cyan-400" />
              <label className="text-sm font-medium text-white">Meditation</label>
            </div>
            <div className="flex items-center gap-2">
              <Clock className="w-4 h-4 text-white/60" />
              <span className="text-xs text-white/60">Minutes:</span>
              <input
                type="number"
                min="0"
                max="120"
                step="5"
                value={planInput.meditationMinutes}
                onChange={(e) => setPlanInput({ ...planInput, meditationMinutes: parseInt(e.target.value) })}
                className="w-20 px-2 py-1 rounded-lg bg-black/40 border border-white/10 text-white text-sm outline-none focus:border-cyan-500/50"
              />
            </div>
          </div>
          
          <div className="glass-card rounded-xl p-4 space-y-3">
            <div className="flex items-center gap-2 mb-2">
              <Target className="w-4 h-4 text-amber-400" />
              <label className="text-sm font-medium text-white">Tasks</label>
            </div>
            <input
              type="text"
              placeholder="e.g., Complete assignment, Review notes (comma separated)"
              value={planInput.tasks}
              onChange={(e) => setPlanInput({ ...planInput, tasks: e.target.value })}
              className="w-full px-3 py-2 rounded-lg bg-black/40 border border-white/10 text-white text-sm outline-none focus:border-amber-500/50"
            />
          </div>
          
          <div className="glass-card rounded-xl p-4 space-y-3">
            <div className="flex items-center gap-2 mb-2">
              <Award className="w-4 h-4 text-pink-400" />
              <label className="text-sm font-medium text-white">Goals</label>
            </div>
            <input
              type="text"
              placeholder="e.g., Learn Python, Read 10 books (comma separated)"
              value={planInput.goals}
              onChange={(e) => setPlanInput({ ...planInput, goals: e.target.value })}
              className="w-full px-3 py-2 rounded-lg bg-black/40 border border-white/10 text-white text-sm outline-none focus:border-pink-500/50"
            />
          </div>
          
          <div className="glass-card rounded-xl p-4 space-y-3">
            <div className="flex items-center gap-2 mb-2">
              <Flame className="w-4 h-4 text-orange-400" />
              <label className="text-sm font-medium text-white">Habits</label>
            </div>
            <input
              type="text"
              placeholder="e.g., Drink water, Sleep 8 hours (comma separated)"
              value={planInput.habits}
              onChange={(e) => setPlanInput({ ...planInput, habits: e.target.value })}
              className="w-full px-3 py-2 rounded-lg bg-black/40 border border-white/10 text-white text-sm outline-none focus:border-orange-500/50"
            />
          </div>
          
          <div className="glass-card rounded-xl p-4">
            <div className="flex items-center gap-2 mb-3">
              <Star className="w-4 h-4 text-yellow-400" />
              <label className="text-sm font-medium text-white">Priority Level</label>
            </div>
            <div className="flex gap-2">
              {['low', 'medium', 'high'].map(level => (
                <button
                  key={level}
                  onClick={() => setPlanInput({ ...planInput, priority: level })}
                  className={`flex-1 px-3 py-2 rounded-lg text-sm capitalize transition-all ${
                    planInput.priority === level 
                      ? 'bg-violet-500/20 text-violet-400 border border-violet-500/30' 
                      : 'bg-black/40 text-white/60 hover:bg-white/5'
                  }`}
                >
                  {level}
                </button>
              ))}
            </div>
          </div>
        </div>
        
        <div className="flex gap-3 mt-6">
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={generatePlan}
            disabled={isGenerating}
            className="flex-1 px-6 py-3 rounded-xl bg-gradient-to-r from-violet-500 to-cyan-500 text-white font-medium flex items-center justify-center gap-2 disabled:opacity-50"
          >
            {isGenerating ? (
              <>
                <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white" />
                Generating...
              </>
            ) : (
              <>
                <Sparkles className="w-5 h-5" />
                Generate Plan
              </>
            )}
          </motion.button>
          
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={() => setShowPlanInput(false)}
            className="px-6 py-3 rounded-xl bg-black/40 text-white/60 font-medium hover:bg-white/10 transition-colors"
          >
            Cancel
          </motion.button>
        </div>
      </div>
    )
  }
  
  return (
    <div className="w-full h-full min-h-[600px] bg-black/40 rounded-2xl overflow-hidden border border-white/10">
      {/* Header */}
      <div className="p-4 border-b border-white/10">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-gradient-to-r from-violet-500 to-cyan-500">
              <Sparkles className="w-5 h-5 text-white" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white">{plan.title}</h2>
              <p className="text-xs text-white/60">{new Date(plan.date).toLocaleDateString()}</p>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={() => setShowPlanInput(true)}
              className="p-2 rounded-lg bg-violet-500/20 text-violet-400 hover:bg-violet-500/30 transition-colors"
              title="Regenerate Plan"
            >
              <RotateCcw className="w-4 h-4" />
            </motion.button>
            
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={exportPlan}
              className="p-2 rounded-lg bg-cyan-500/20 text-cyan-400 hover:bg-cyan-500/30 transition-colors"
              title="Export Plan"
            >
              <Download className="w-4 h-4" />
            </motion.button>
          </div>
        </div>
      </div>
      
      {/* Progress Bar */}
      <div className="px-4 py-3 border-b border-white/10">
        <div className="flex items-center justify-between mb-2">
          <span className="text-xs text-white/60">Daily Progress</span>
          <span className="text-sm font-bold text-white">{progress.toFixed(0)}%</span>
        </div>
        <div className="w-full h-2 rounded-full bg-black/40 overflow-hidden">
          <motion.div
            initial={{ width: 0 }}
            animate={{ width: `${progress}%` }}
            transition={{ duration: 0.5 }}
            className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-500"
          />
        </div>
      </div>
      
      {/* Controls */}
      <div className="p-4 border-b border-white/10">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            {/* View Mode */}
            <div className="flex gap-1">
              {['checklist', 'timeline', 'stats'].map(mode => (
                <button
                  key={mode}
                  onClick={() => setViewMode(mode)}
                  className={`px-3 py-1.5 rounded-lg text-xs capitalize transition-all ${
                    viewMode === mode 
                      ? 'bg-violet-500/20 text-violet-400 border border-violet-500/30' 
                      : 'bg-black/40 text-white/60 hover:bg-white/5'
                  }`}
                >
                  {mode}
                </button>
              ))}
            </div>
            
            {/* Filter */}
            <div className="flex gap-1 ml-2">
              {['all', 'pending', 'completed'].map(status => (
                <button
                  key={status}
                  onClick={() => setFilterStatus(status)}
                  className={`px-3 py-1.5 rounded-lg text-xs capitalize transition-all ${
                    filterStatus === status 
                      ? 'bg-cyan-500/20 text-cyan-400 border border-cyan-500/30' 
                      : 'bg-black/40 text-white/60 hover:bg-white/5'
                  }`}
                >
                  {status}
                </button>
              ))}
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            {/* Search */}
            <div className="relative">
              <Search className="w-4 h-4 text-white/60 absolute left-2 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Search items..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-8 pr-3 py-1.5 rounded-lg bg-black/40 border border-white/10 text-white text-xs outline-none focus:border-violet-500/50 w-40"
              />
            </div>
            
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={() => setShowDetails(!showDetails)}
              className="p-2 rounded-lg bg-black/40 text-white/60 hover:bg-white/10 transition-colors"
            >
              {showDetails ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
            </motion.button>
          </div>
        </div>
      </div>
      
      {/* Content */}
      <div className="p-4 overflow-y-auto" style={{ maxHeight: 'calc(100% - 200px)' }}>
        {viewMode === 'checklist' && (
          <div className="space-y-2">
            {filteredItems.map((item, index) => {
              const CategoryIcon = getCategoryIcon(item.category)
              const isCompleted = completedItems[item.id]
              
              return (
                <motion.div
                  key={item.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.05 }}
                  className={`glass-card rounded-xl p-3 transition-all ${
                    isCompleted ? 'opacity-60' : ''
                  }`}
                >
                  <div className="flex items-start gap-3">
                    <button
                      onClick={() => toggleItemComplete(item.id)}
                      className={`mt-1 w-5 h-5 rounded-full border-2 flex items-center justify-center transition-all ${
                        isCompleted 
                          ? 'bg-emerald-500 border-emerald-500' 
                          : 'border-white/30 hover:border-violet-500'
                      }`}
                    >
                      {isCompleted && <Check className="w-3 h-3 text-white" />}
                    </button>
                    
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <CategoryIcon className="w-4 h-4 text-white/60" />
                        <h3 className={`text-sm font-medium ${isCompleted ? 'line-through text-white/40' : 'text-white'}`}>
                          {item.title}
                        </h3>
                        <span className={`text-xs font-medium ${getPriorityColor(item.priority)}`}>
                          {item.priority}
                        </span>
                      </div>
                      
                      {showDetails && (
                        <div className="space-y-1">
                          <p className="text-xs text-white/60">{item.description}</p>
                          <div className="flex items-center gap-3 text-xs text-white/40">
                            <span className="flex items-center gap-1">
                              <Clock className="w-3 h-3" />
                              {item.duration} min
                            </span>
                            <span className="flex items-center gap-1">
                              <Calendar className="w-3 h-3" />
                              {item.timeSlot}
                            </span>
                          </div>
                        </div>
                      )}
                    </div>
                    
                    <button
                      onClick={() => removeItem(item.id)}
                      className="p-1 rounded hover:bg-white/10 transition-colors"
                    >
                      <Trash2 className="w-4 h-4 text-white/40 hover:text-red-400" />
                    </button>
                  </div>
                </motion.div>
              )
            })}
            
            {/* Add Item Button */}
            <motion.button
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              onClick={() => addItem('custom', prompt('Enter item title:'))}
              className="w-full p-3 rounded-xl border-2 border-dashed border-white/20 text-white/60 hover:border-violet-500/50 hover:text-violet-400 transition-all flex items-center justify-center gap-2"
            >
              <Plus className="w-4 h-4" />
              Add Custom Item
            </motion.button>
          </div>
        )}
        
        {viewMode === 'timeline' && (
          <div className="space-y-4">
            {['morning', 'afternoon', 'evening', 'flexible', 'daily'].map(timeSlot => {
              const slotItems = filteredItems.filter(item => item.timeSlot === timeSlot)
              if (slotItems.length === 0) return null
              
              return (
                <div key={timeSlot}>
                  <h3 className="text-sm font-bold text-white/60 mb-2 capitalize">{timeSlot}</h3>
                  <div className="space-y-2">
                    {slotItems.map((item) => {
                      const CategoryIcon = getCategoryIcon(item.category)
                      const isCompleted = completedItems[item.id]
                      
                      return (
                        <motion.div
                          key={item.id}
                          className={`glass-card rounded-xl p-3 flex items-center gap-3 ${
                            isCompleted ? 'opacity-60' : ''
                          }`}
                        >
                          <button
                            onClick={() => toggleItemComplete(item.id)}
                            className={`w-5 h-5 rounded-full border-2 flex items-center justify-center ${
                              isCompleted 
                                ? 'bg-emerald-500 border-emerald-500' 
                                : 'border-white/30'
                            }`}
                          >
                            {isCompleted && <Check className="w-3 h-3 text-white" />}
                          </button>
                          
                          <CategoryIcon className="w-4 h-4 text-white/60" />
                          
                          <div className="flex-1">
                            <h4 className={`text-sm ${isCompleted ? 'line-through text-white/40' : 'text-white'}`}>
                              {item.title}
                            </h4>
                            <p className="text-xs text-white/40">{item.duration} min</p>
                          </div>
                          
                          <span className={`text-xs font-medium ${getPriorityColor(item.priority)}`}>
                            {item.priority}
                          </span>
                        </motion.div>
                      )
                    })}
                  </div>
                </div>
              )
            })}
          </div>
        )}
        
        {viewMode === 'stats' && analytics && (
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-3">
              <div className="glass-card rounded-xl p-4">
                <div className="text-xs text-white/60 mb-1">Total Items</div>
                <div className="text-2xl font-bold text-white">{analytics.totalItems}</div>
              </div>
              
              <div className="glass-card rounded-xl p-4">
                <div className="text-xs text-white/60 mb-1">Completed</div>
                <div className="text-2xl font-bold text-emerald-400">{analytics.completedCount}</div>
              </div>
              
              <div className="glass-card rounded-xl p-4">
                <div className="text-xs text-white/60 mb-1">Completion Rate</div>
                <div className="text-2xl font-bold text-violet-400">{analytics.completionRate.toFixed(0)}%</div>
              </div>
              
              <div className="glass-card rounded-xl p-4">
                <div className="text-xs text-white/60 mb-1">Total Time</div>
                <div className="text-2xl font-bold text-cyan-400">{Math.round(analytics.estimatedTime)} min</div>
              </div>
            </div>
            
            <div className="glass-card rounded-xl p-4">
              <h3 className="text-sm font-bold text-white mb-3">By Category</h3>
              <div className="space-y-2">
                {Object.entries(analytics.byCategory).map(([category, data]) => {
                  const CategoryIcon = getCategoryIcon(category)
                  const percent = data.total > 0 ? (data.completed / data.total) * 100 : 0
                  
                  return (
                    <div key={category} className="flex items-center gap-3">
                      <CategoryIcon className="w-4 h-4 text-white/60" />
                      <div className="flex-1">
                        <div className="flex items-center justify-between mb-1">
                          <span className="text-xs text-white capitalize">{category}</span>
                          <span className="text-xs text-white/60">{data.completed}/{data.total}</span>
                        </div>
                        <div className="w-full h-1.5 rounded-full bg-black/40">
                          <div 
                            className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-500"
                            style={{ width: `${percent}%` }}
                          />
                        </div>
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
            
            <div className="glass-card rounded-xl p-4">
              <h3 className="text-sm font-bold text-white mb-3">Priority Distribution</h3>
              <div className="flex items-center gap-4">
                {Object.entries(analytics.priorityDistribution).map(([priority, count]) => (
                  <div key={priority} className="flex-1 text-center">
                    <div className={`text-lg font-bold ${getPriorityColor(priority)}`}>{count}</div>
                    <div className="text-xs text-white/60 capitalize">{priority}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
